---
- name: install python packages via pip3
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state | default('latest') }}"
    executable: /usr/bin/pip3
  with_items:
    - "{{ pip3_packages }}"