---
    - name: Pylama - initial virtualenv
      command: virtualenv /home/vagrant/venvs/pylama -p python3.4 creates="/user/home/venvs/pylama"
    
    - name: Pylama - install
      pip: 
        name={{item}} 
        executable="/home/vagrant/venvs/coala/bin/pip3" 
        state=latest
        extra_args='--upgrade'
      with_items:
        - pylama
        - pylama_pylint
        - pympler

