---
    - name: Pylama - initial virtualenv
      command: virtualenv /home/vagrant/venvs/pylama -p python3.4 creates="/home/vagrant/venvs/pylama"

    - name: Pylama - install
      pip: 
        name={{item}} 
        executable="/home/vagrant/venvs/pylama/bin/pip3" 
        state=latest
        extra_args='--upgrade'
      with_items:
        - pip
        - pylama
        - pylama_pylint
        - pympler
        - memory_profiler
        - psutil
